### PR TITLE
Use custom Docker image to avoid boilerplate bloat

### PR DESCRIPTION
**Pull request by armanbilge**
This repo is very helpful! But I didn't like the idea of having to copy boilerplate scripts to every repo I work on. So I condensed it into a single Docker image (based on Gitpod's image) that's really easy to use from the `.gitpod.yml`. This also makes distributing updates much easier.

https://github.com/armanbilge/metals-gitpod/

PS Apologies for this empty PR, since there was no way to make an issue. But if this is interesting to you, I'm happy to rework your sample to use the Docker image. Also open to feedback.

### CODE REVIEW

**Comment by tgodzik** [comment]
Thanks for reaching out! I think it might be useful to create ready to use docker containers, though I have never had much experience with publishing them, which is why I never taken this up.

I think we could publish containers under `scalameta` namespace though I am not sure yet how we can claim the namespace. Would that be ok with you?

**Comment by armanbilge** [comment]
Thanks for your interest! This is my first published Docker container too. Turned out to be quite easy: if you have a repo with a Dockerfile in it, you can link it to your Dockerhub account so it builds and publishes completely automatically. If you can set up a repository for this then I can make a PR there if you wish. To claim the namespace you should make an account/organization at https://hub.docker.com.

**Comment by tgodzik** [comment]
Ok cool, I will discuss it with the other in the organization and probably look into it next week.

**Comment by armanbilge** [comment]
I now use the default gitpod image with `sdk install sbt` to get setup.

**Pull request closed without merging**
